on: push
permissions:
  contents: write
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run:
          npm install
          npm run build

      - name: Run a script
        run: echo "Hello, World!"

      - name: Run tests
        run: echo "Running tests..."

      - name: node version
        run: node --version
      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          token: ${{ secrets.GITHUB_TOKEN }}