on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: echo "Hello, World!"

      - name: Run tests
        run: echo "Running tests..."

      - name: node version
        run: node --version
